 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-generator:$COMMIT_SHA', './cloud-generator']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/cloud-generator:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'cloud-generator'
   - '--image'
   - 'gcr.io/$PROJECT_ID/cloud-generator:$COMMIT_SHA'
   - '--region'
   - 'europe-north1'
 images:
 - 'gcr.io/$PROJECT_ID/cloud-generator:$COMMIT_SHA'